version: '3.3'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:8777"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

