version: '3.3'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:8777"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - selenium-hub
      - chrome

  selenium-hub:
    image: selenium/hub:4.1.2-20220217
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_OPTS="--host 0.0.0.0"

  chrome:
    image: selenium/node-chrome:4.1.2-20220217
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
