version: '3.3'



services:
  web:
    container_name: wog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:5000"
    volumes:
      - "./:/app"
    networks:
      - my_app

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - my_app

  chrome:
    shm_size: 2g
    image: selenium/node-chrome:latest
    container_name: selenium-hub-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - my_app

networks:
  my_app:
    driver: bridge